import type { CitySlug, Run } from "@/lib/types";

export const seedRuns: Run[] = [
  {
    id: "sg-1",
    city: "sg",
    locationName: "Marina Bay waterfront",
    route: "Helix Bridge -> Marina Barrage",
    lat: 1.2869,
    lng: 103.861,
    day: "SUN",
    runDate: "2026-05-10",
    time: "07:00",
    paceMin: "5:15",
    paceMax: "5:30",
    distanceKm: 8,
    goal: "Easy",
    spotsTotal: 2,
    spotsTaken: 1,
    womenOnly: false,
    status: "active",
    clubName: "solo run",
    organiser: { name: "Mei", avatarInitial: "M", runs: 18, rating: 4.9, verified: true }
  },
  {
    id: "sg-2",
    city: "sg",
    locationName: "East Coast sunrise",
    route: "Fort Road -> Bedok Jetty",
    lat: 1.3028,
    lng: 103.9123,
    day: "SAT",
    runDate: "2026-05-09",
    time: "06:30",
    paceMin: "5:30",
    paceMax: "6:00",
    distanceKm: 7,
    goal: "Social",
    spotsTotal: 2,
    spotsTaken: 0,
    womenOnly: false,
    status: "active",
    clubName: "solo run",
    organiser: { name: "Jun", avatarInitial: "J", runs: 22, rating: 4.8, verified: true }
  },
  {
    id: "sg-3",
    city: "sg",
    locationName: "Bishan Park loop",
    route: "Bishan-Ang Mo Kio Park loop",
    lat: 1.3638,
    lng: 103.8454,
    day: "TUE",
    runDate: "2026-05-12",
    time: "18:45",
    paceMin: "5:45",
    paceMax: "6:15",
    distanceKm: 5,
    goal: "Recovery",
    spotsTotal: 2,
    spotsTaken: 0,
    womenOnly: true,
    status: "active",
    clubName: "solo run",
    organiser: { name: "Asha", avatarInitial: "A", runs: 14, rating: 4.9, verified: true }
  },
  {
    id: "sg-4",
    city: "sg",
    locationName: "Southern Ridges",
    route: "HortPark -> Henderson Waves",
    lat: 1.2781,
    lng: 103.8116,
    day: "WED",
    runDate: "2026-05-06",
    time: "07:15",
    paceMin: "5:30",
    paceMax: "6:00",
    distanceKm: 6,
    goal: "Hills",
    spotsTotal: 1,
    spotsTaken: 0,
    womenOnly: false,
    status: "active",
    clubName: "Ridge Runners",
    organiser: { name: "Ravi", avatarInitial: "R", runs: 31, rating: 4.7, verified: true }
  },
  {
    id: "sg-5",
    city: "sg",
    locationName: "Sentosa beach path",
    route: "Beach Station -> Tanjong Beach",
    lat: 1.2494,
    lng: 103.8303,
    day: "FRI",
    runDate: "2026-05-08",
    time: "18:30",
    paceMin: "6:00",
    paceMax: "6:30",
    distanceKm: 5,
    goal: "Easy",
    spotsTotal: 3,
    spotsTaken: 1,
    womenOnly: false,
    status: "active",
    clubName: "solo run",
    organiser: { name: "Nora", avatarInitial: "N", runs: 9, rating: 4.8, verified: true }
  },
  {
    id: "sg-6",
    city: "sg",
    locationName: "Kallang River tempo",
    route: "Stadium -> Tanjong Rhu",
    lat: 1.302,
    lng: 103.8738,
    day: "THU",
    runDate: "2026-05-07",
    time: "19:00",
    paceMin: "5:00",
    paceMax: "5:30",
    distanceKm: 6,
    goal: "Tempo",
    spotsTotal: 1,
    spotsTaken: 1,
    womenOnly: false,
    status: "full",
    clubName: "Kallang Tempo",
    organiser: { name: "Leo", avatarInitial: "L", runs: 45, rating: 4.9, verified: true }
  },
  {
    id: "bcn-1",
    city: "bcn",
    locationName: "Barceloneta boardwalk",
    route: "Barceloneta -> Port Olimpic",
    lat: 41.3789,
    lng: 2.1899,
    day: "SAT",
    runDate: "2026-05-09",
    time: "07:00",
    paceMin: "5:00",
    paceMax: "5:30",
    distanceKm: 6,
    goal: "Easy",
    spotsTotal: 2,
    spotsTaken: 0,
    womenOnly: false,
    status: "active",
    clubName: "solo run",
    organiser: { name: "Marc", avatarInitial: "M", runs: 24, rating: 4.8, verified: true }
  },
  {
    id: "bcn-2",
    city: "bcn",
    locationName: "Ciutadella Park loop",
    route: "Arc de Triomf -> Parc Zoologic",
    lat: 41.3863,
    lng: 2.1862,
    day: "SUN",
    runDate: "2026-05-10",
    time: "08:00",
    paceMin: "5:30",
    paceMax: "6:00",
    distanceKm: 5,
    goal: "Social",
    spotsTotal: 1,
    spotsTaken: 0,
    womenOnly: true,
    status: "active",
    clubName: "solo run",
    organiser: { name: "Clara", avatarInitial: "C", runs: 12, rating: 4.9, verified: true }
  },
  {
    id: "bcn-3",
    city: "bcn",
    locationName: "Montjuic hill loop",
    route: "Placa Espanya -> Castell de Montjuic",
    lat: 41.3643,
    lng: 2.1531,
    day: "WED",
    runDate: "2026-05-06",
    time: "06:30",
    paceMin: "5:30",
    paceMax: "6:00",
    distanceKm: 8,
    goal: "Hills",
    spotsTotal: 1,
    spotsTaken: 0,
    womenOnly: false,
    status: "active",
    clubName: "Barcelona Trail Runners",
    organiser: { name: "Jordi", avatarInitial: "J", runs: 41, rating: 4.7, verified: true }
  },
  {
    id: "bcn-4",
    city: "bcn",
    locationName: "Collserola ridge",
    route: "Tibidabo -> Sant Pere Martir",
    lat: 41.4219,
    lng: 2.119,
    day: "SAT",
    runDate: "2026-05-09",
    time: "07:30",
    paceMin: "5:30",
    paceMax: "6:00",
    distanceKm: 12,
    goal: "Trail",
    spotsTotal: 1,
    spotsTaken: 1,
    womenOnly: false,
    status: "full",
    clubName: "Collserola Trail Club",
    organiser: { name: "Pau", avatarInitial: "P", runs: 67, rating: 5, verified: true }
  }
];

export function getSeedRuns(city: CitySlug): Run[] {
  return seedRuns.filter((run) => run.city === city);
}

export function paceLabel(run: Pick<Run, "paceMin" | "paceMax">) {
  return `${run.paceMin}-${run.paceMax}`;
}

export function openSpots(run: Pick<Run, "spotsTotal" | "spotsTaken">) {
  return Math.max(0, run.spotsTotal - run.spotsTaken);
}
